version: "3.9"
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: validate_emails
    working_dir: /validate_emails
    volumes:
      - ./:/validate_emails